name: Lint

on: [pull_request, push]

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      src: ${{ steps.changes.outputs.src }}
      srctauri: ${{ steps.changes.outputs.srctauri }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          src:
            - 'src/**'
          srctauri:
            - 'src-tauri/**'

  eslint:
    name: eslint
    needs: changes
    if: needs.changes.outputs.src == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - uses: reviewdog/action-eslint@v1
        if: github.event_name == 'push'
        with:
          reporter: github-check
          eslint_flags: 'src/'
      - uses: reviewdog/action-eslint@v1
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: 'src/'

  clippy_check:
    name: clippy check
    needs: changes
    if: needs.changes.outputs.srctauri == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          key: clippy
          workspaces: |
            src-tauri

      - name: install dependencies
        run: |
          mkdir -p dist
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf libasound2-dev

      - uses: sksat/action-clippy@main
        if: github.event_name == 'push'
        with:
          working_directory: ./src-tauri
          reporter: github-check

      - uses: sksat/action-clippy@main
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: ./src-tauri
          reporter: github-pr-review
